import { CarSharingTariff } from "./types";

export const INITIAL_TARIFFS: CarSharingTariff[] = [
  {
    id: "enjoy-1h",
    providerName: "Enjoy",
    tariffName: "Pacchetto 1 Ora",
    unitType: "hour",
    unitValue: 1,
    unitCost: 14.0,
    extraMinutePrice: 0.29,
    kmIncluded: 50,
    pricePerExtraKm: 0.29,
    unlockFee: 0,
    color: "#e11d48",
    type: "free-floating",
  },
  {
    id: "enjoy-3h",
    providerName: "Enjoy",
    tariffName: "Pacchetto 3 Ore",
    unitType: "hour",
    unitValue: 3,
    unitCost: 20.0,
    extraMinutePrice: 0.29,
    kmIncluded: 50,
    pricePerExtraKm: 0.29,
    unlockFee: 0,
    color: "#e11d48",
    type: "free-floating",
  },
  {
    id: "sharenow-2h",
    providerName: "Share Now",
    tariffName: "Pacchetto 2 Ore",
    unitType: "hour",
    unitValue: 2,
    unitCost: 17.99,
    extraMinutePrice: 0.19,
    kmIncluded: 40,
    pricePerExtraKm: 0.29,
    unlockFee: 0,
    color: "#1e293b",
    type: "free-floating",
  },
  {
    id: "e-vai-1h",
    providerName: "E-Vai",
    tariffName: "Tariffa Oraria",
    unitType: "hour",
    unitValue: 1,
    unitCost: 6.0,
    extraMinutePrice: 0.10,
    kmIncluded: 0,
    pricePerExtraKm: 0.19,
    unlockFee: 2.0,
    color: "#16a34a",
    type: "station-based",
  },
  {
    id: "zity-1h",
    providerName: "Zity",
    tariffName: "Tariffa Oraria",
    unitType: "hour",
    unitValue: 1,
    unitCost: 13.80,
    extraMinutePrice: 0.23,
    kmIncluded: 0,
    pricePerExtraKm: 0,
    unlockFee: 0,
    color: "#84cc16",
    type: "free-floating",
  }
];
